# Configuration for Faye Text

# Font configuration
font:
  family: FiraCode
  style: SemiBold
  size: 10

# Code highlight configuration
highlight:
  status: on

# Cursor style configuration
# Values for `style`:
#     - ▇ block
#     - _ underline
#     - | line
# Values for `blinking`:
#     - off: Disable blinking by default
#     - on: Enable blinking
cursor:
  style: underline
  blinking: off
