[package]
name = "lc_core"
version = "0.1.0"
authors = ["irisoulenx <howiewoo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "lc_core"
crate-type = ["cdylib"]
