[package]
name = "lib-core"
version = "0.1.0"
authors = ["Howie Woo <howiewoo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
